services:
  bot:
    build:
      context: .
    env_file:
      - .env
    restart: unless-stopped
    command: ["run"]
    volumes:
      - ./reports:/app/reports
      - ./configs:/app/configs:ro

  cli:
    build:
      context: .
    env_file:
      - .env
    entrypoint: ["money-dahong"]
    profiles: ["cli"]
    volumes:
      - ./reports:/app/reports
      - ./configs:/app/configs:ro
